//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavniSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meal()
        {
            this.Namirnices = new HashSet<Namirnice>();
        }
    
        public int ID_Meals { get; set; }
        public string Meals { get; set; }
        public Nullable<int> Masti { get; set; }
        public Nullable<int> Bjelancevine { get; set; }
        public Nullable<int> Ugljikohidrati { get; set; }
        public string Suma { get; set; }
        public string VridiDo { get; set; }
        public string VridiOd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Namirnice> Namirnices { get; set; }
    }
}
