//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavniSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class praEntities10 : DbContext
    {
        public praEntities10()
            : base("name=praEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meals> Meals { get; set; }
        public virtual DbSet<Namirnice> Namirnice { get; set; }
        public virtual DbSet<TipNamirnice> TipNamirnice { get; set; }
    
        public virtual ObjectResult<povijest_Result> povijest(Nullable<System.DateTime> datum, Nullable<System.DateTime> end)
        {
            var datumParameter = datum.HasValue ?
                new ObjectParameter("datum", datum) :
                new ObjectParameter("datum", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<povijest_Result>("povijest", datumParameter, endParameter);
        }
    
        public virtual ObjectResult<Namirnice> Povists(Nullable<System.DateTime> datum, Nullable<System.DateTime> end)
        {
            var datumParameter = datum.HasValue ?
                new ObjectParameter("datum", datum) :
                new ObjectParameter("datum", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Namirnice>("Povists", datumParameter, endParameter);
        }
    
        public virtual ObjectResult<Namirnice> Povists(Nullable<System.DateTime> datum, Nullable<System.DateTime> end, MergeOption mergeOption)
        {
            var datumParameter = datum.HasValue ?
                new ObjectParameter("datum", datum) :
                new ObjectParameter("datum", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Namirnice>("Povists", mergeOption, datumParameter, endParameter);
        }
    }
}
