//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicSite.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registracija
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Spol { get; set; }
        public string Tip { get; set; }
        public string Aktivost { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Sifra { get; set; }
        public Nullable<int> Kalorije { get; set; }
        public Nullable<int> Tezina { get; set; }
        public Nullable<int> Visina { get; set; }
        public string DatumRodenja { get; set; }
        public int ID_registracija { get; set; }
    }
}
