//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Namirnice
    {
        public string Namirnica { get; set; }
        public string Kjuli { get; set; }
        public string Kcal { get; set; }
        public int ID_namirnice { get; set; }
        public Nullable<int> TipNamirnice_ID { get; set; }
        public Nullable<int> mjerna_id { get; set; }
        public string MjernaJedinica { get; set; }
        public Nullable<int> ObrokID { get; set; }
        public Nullable<System.DateTime> DatumJelovnika { get; set; }
        public Nullable<int> Mjerna_IDs { get; set; }
        public Nullable<int> Kolicina { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Meal Meal1 { get; set; }
        public virtual TipNamirnice TipNamirnice { get; set; }
        public virtual TipNamirnice TipNamirnice1 { get; set; }
    }
}
